### ISSUE TITLE
[PE-D][Tester E] Documentation: .JAR does not open on double click

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-4/tp#151]
On mac, this functionality does not work. 

![image.png](https://raw.githubusercontent.com/starsia/ped/main/files/da3177fc-afa1-4587-b496-3b48bc0a6af3.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: starsia/ped#15

**Comment by Rishit02** [comment]
Please use the suggested method to open JAR files:
Run the jar file in the following manner:

- Put the jar file in an empty folder, to prevent data files created by other jar files you tested earlier from interfering with the current jar file.
- Open a terminal, and navigate to the folder you put the JAR file in.
-  Run the java -version command to confirm you are using Java 11.
-  Mac user, confirm you are using the exact Java distribution we have prescribed [here](https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html).
- Run the jar file using the java -jar {file_name} command (rather than double-clicking) in the same terminal.
